# Configuration parameters: AllowURI.
Metrics/LineLength:
  Max: 225

# Configuration parameters: CountKeywordArgs.
Metrics/ParameterLists:
  Max: 6

Metrics/BlockNesting:
  Max: 4

# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 174

Metrics/CyclomaticComplexity:
  Max: 7

# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 76

Metrics/PerceivedComplexity:
  Max: 8

